name: Deploy to cluster (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 \
        | docker login --username AWS --password-stdin 718159740586.dkr.ecr.ap-south-1.amazonaws.com

    # ðŸ”¹ Backend (server)
    - name: Build & Push Backend
      run: |
        docker build -t wanderlust-backend ./server
        docker tag wanderlust-backend:latest 718159740586.dkr.ecr.ap-south-1.amazonaws.com/wanderlust:backend
        docker push 718159740586.dkr.ecr.ap-south-1.amazonaws.com/wanderlust:backend

    # ðŸ”¹ Frontend (client)
    - name: Build & Push Frontend
      run: |
        docker build -t wanderlust-frontend ./client
        docker tag wanderlust-frontend:latest 718159740586.dkr.ecr.ap-south-1.amazonaws.com/wanderlust:frontend
        docker push 718159740586.dkr.ecr.ap-south-1.amazonaws.com/wanderlust:frontend

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region ap-south-1 \
          --name my-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s
